# SPDX-FileCopyrightText: (C) 2025 Rivos Inc.
# SPDX-License-Identifier: Apache-2.0

version = 1

# Design files
[[annotations]]
path = [
  "**.kicad_sch",
  "**.kicad_pro",
  "**.brd",
]
SPDX-FileCopyrightText  = "(C) 2025 Rivos Inc."
SPDX-License-Identifier = "CERN-OHL-P-2.0+"
